#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/snoopy/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/snoopy/Documents/github/flutter_factory"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/snoopy/flutter/bin/cache/artifacts/engine/ios-release"
export "FLUTTER_BUILD_NAME=0.1.3"
export "FLUTTER_BUILD_NUMBER=3"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=.packages"
